// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBW2os1ccvKVuGZNI-EdU082nv6Ls4el0',
    appId: '1:193787016498:web:7de4a0739062eeba2d932b',
    messagingSenderId: '193787016498',
    projectId: 'glideguide',
    authDomain: 'glideguide.firebaseapp.com',
    storageBucket: 'glideguide.appspot.com',
    measurementId: 'G-FRNMHY0TTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFX3y4vJoAeOGD8KEz-1LFo__pSBXUy8',
    appId: '1:193787016498:android:b0cf001d0e87b6ef2d932b',
    messagingSenderId: '193787016498',
    projectId: 'glideguide',
    storageBucket: 'glideguide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHR11f35198iJo8NiQgUjhpNrIkPJOEE',
    appId: '1:193787016498:ios:ceda014154e9a9652d932b',
    messagingSenderId: '193787016498',
    projectId: 'glideguide',
    storageBucket: 'glideguide.appspot.com',
    iosBundleId: 'com.example.glideguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHR11f35198iJo8NiQgUjhpNrIkPJOEE',
    appId: '1:193787016498:ios:3d9f577751c875e92d932b',
    messagingSenderId: '193787016498',
    projectId: 'glideguide',
    storageBucket: 'glideguide.appspot.com',
    iosBundleId: 'com.example.glideguide.RunnerTests',
  );
}
